# Generated by Django 4.2.14 on 2026-01-28 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(help_text='Teléfono de contacto (ej: +1-2025551234 o 2025551234)', max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Formato esperado: +XX-XXXXXXXXX o 123456789', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '⭐ Muy malo'), (2, '⭐⭐ Malo'), (3, '⭐⭐⭐ Regular'), (4, '⭐⭐⭐⭐ Bueno'), (5, '⭐⭐⭐⭐⭐ Excelente')], help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
